Traceback (most recent call last):
  File "/Users/alessandro/PycharmProjects/Palestra_bot/main.py", line 1718, in thread_telegram
    bot.polling(none_stop=True)
  File "/Users/alessandro/PycharmProjects/testindg/Palestra_bot/lib/python3.10/site-packages/telebot/__init__.py", line 1043, in polling
    self.__threaded_polling(non_stop=non_stop, interval=interval, timeout=timeout, long_polling_timeout=long_polling_timeout,
  File "/Users/alessandro/PycharmProjects/testindg/Palestra_bot/lib/python3.10/site-packages/telebot/__init__.py", line 1118, in __threaded_polling
    raise e
  File "/Users/alessandro/PycharmProjects/testindg/Palestra_bot/lib/python3.10/site-packages/telebot/__init__.py", line 1074, in __threaded_polling
    self.worker_pool.raise_exceptions()
  File "/Users/alessandro/PycharmProjects/testindg/Palestra_bot/lib/python3.10/site-packages/telebot/util.py", line 147, in raise_exceptions
    raise self.exception_info
  File "/Users/alessandro/PycharmProjects/testindg/Palestra_bot/lib/python3.10/site-packages/telebot/util.py", line 90, in run
    task(*args, **kwargs)
  File "/Users/alessandro/PycharmProjects/testindg/Palestra_bot/lib/python3.10/site-packages/telebot/__init__.py", line 6770, in _run_middlewares_and_handler
    result = handler['function'](message)
  File "/Users/alessandro/PycharmProjects/Palestra_bot/main.py", line 1655, in callback
    new_dizAll_idx = int(after_code[1:]) if int(after_code[1:]) in list(TYPE_TO_DIZALL_IDX.keys()) else None  # idx del nuovo esercizio
ValueError: invalid literal for int() with base 10: 'Nome'
